let i = 0x00;
const xoxISA = {
  'nop': i++,
  'movrr': i++,
  'movra': i++,
  'movar': i++,
  'movir': i++,
  'movia': i++,
  'pshr': i++,
  'psha': i++,
  'pshi': i++,
  'popr': i++,
  'popa': i++,
  'lea': i++,
  'addrr': i++,
  'addra': i++,
  'addar': i++,
  'addri': i++,
  'addai': i++,
  'subrr': i++,
  'subra': i++,
  'subar': i++,
  'subri': i++,
  'subai': i++,
  'mulrr': i++,
  'mulra': i++,
  'divr': i++,
  'diva': i++,
  'andrr': i++,
  'andra': i++,
  'andar': i++,
  'andri': i++,
  'andai': i++,
  'orrrr': i++,
  'orrra': i++,
  'orrar': i++,
  'orrri': i++,
  'orrai': i++,
  'xorrr': i++,
  'xorra': i++,
  'xorar': i++,
  'xorri': i++,
  'xorai': i++,
  'notr': i++,
  'nota': i++,
  'sllri': i++,
  'sllrr': i++,
  'sllai': i++,
  'sllar': i++,
  'slrri': i++,
  'slrrr': i++,
  'slrai': i++,
  'slrar': i++,
  'sarri': i++,
  'sarrr': i++,
  'sarai': i++,
  'sarar': i++,
  'cmprr': i++,
  'cmpra': i++,
  'cmpar': i++,
  'cmpri': i++,
  'cmpai': i++,
  'jmp': i++,
  'jeq': i++,
  'jne': i++,
  'jt': i++,
  'jlq': i++,
  'jgt': i++,
  'jgq': i++,
  'cll': i++,
  'ret': i++,
  'stp': i++,
}

const xoxCodes = Object.keys(xoxISA).map((e) => {
  return e;
});

module.exports = {
  xoxISA,
  xoxCodes,
}
